### ISSUE TITLE
Generate address?

### ISSUE THREAD

**Issue by vtm9** [miracle2k/ripple-python#4]
How can I generate ripple address?

**Comment by jeamick** [comment]
https://github.com/ripple/ripple-keypairs could help you bu tit is in JS.

For python you can look at https://github.com/arsenlosenko/python-ripple-lib/blob/master/ripple_api/json_rpc.py on the wallet propose method.

I hope this help @vtm9

**Comment by vtm9** [comment]
Thx, I've used my own implementation
